### PR TITLE
Migrate collections to concurrent implementations

### LINKED ISSUE #28: Migrate synchronized collections to concurrent collections
All synchronized collections need to be migrated to concurrent collections for thread safe use. Using synchronized collections lends itself to non-synchronized access with iterators/streams and blocks all access to the collection in cases where access could be performed concurrently. This was leftover from some old Outside code, and can be cleaned up. 

Tagging internal issue: https://git.liquidcrystalstudios.com/outside/outside/-/issues/202

### PR DESCRIPTION
**Pull request by tlf30**
Closes #28 

@oxplay2, would you mind testing this one?

### CODE REVIEW

**Comment by oxplay2** [comment]
its really hard to test it without some replication.

Any suggestions?

**Comment by tlf30** [comment]
The only strategy I can come up with is writing a fake client that establishes many concurrent connections at the same time repeatedly.

**Comment by oxplay2** [comment]
sorry it took 4 days before i test it.

**i think it work fine, didnt seen any concurrent issues, but sending you logs so you can verify if im correct since there were other warnings/exceptions but looks like proper ones**

i did run 1x server and 3x clients like:


```
public class JmeClientConnectionStressTest extends SimpleApplication {

    NettyClient client;
    float tpfCounter = 0;

    @Override
    public void simpleInitApp() {
    }

    @Override
    public void simpleUpdate(float tpf) {
        if (tpfCounter > 0.01f) {
            tpfCounter = 0;
            if (client != null) {
                stateManager.detach(client);
            }
            client = new NettyClient("test", true, 10000, "localhost");
            stateManager.attach(client);
            client.setLogLevel(LogLevel.INFO);
            client.registerListener(new MessageListener() {
                @Override
                public void onMessage(NetworkMessage msg, NetworkServer server, NetworkClient client) {
                    System.out.println("Got message " + msg);
                }

                @Override
                public Class<? extends NetworkMessage>[] getSupportedMessages() {
                    return new Class[]{TestTCPMessage.class, TestUDPMessage.class, TestTCPBigMessageA.class, TestTCPBigMessageB.class, TestUDPBigMessageA.class, TestUDPBigMessageB.class};
                }
            });
            client.registerListener(new ConnectionListener() {
                @Override
                public void onConnect(NetworkClient client) {
                    client.send(new TestTCPMessage());
                }

                @Override
                public void onDisconnect(NetworkClient client) {

                }
            });
            client.send(new TestTCPMessage());
        }
        tpfCounter += tpf;
    }

    public static void main(String[] args) {
        JmeClientConnectionStressTest client = new JmeClientConnectionStressTest();
        client.start();
    }
}
```


see below logs.

**probably the errors i had were only caused by "closing client before establish/message-sent"**
**(Verify me)**

Client had SEVERE, but server only Warnings.


on client side i only seen errors like:

> INFO: [id: 0xf98c16ef] REGISTERED
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler connect
> INFO: [id: 0xf98c16ef] CONNECT: localhost/127.0.0.1:10000
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0xf98c16ef, L:/127.0.0.1:37424 - R:localhost/127.0.0.1:10000] ACTIVE
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0xf98c16ef, L:/127.0.0.1:37424 ! R:localhost/127.0.0.1:10000] USER_EVENT: SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0xf98c16ef, L:/127.0.0.1:37424 ! R:localhost/127.0.0.1:10000] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelInactive
> INFO: [id: 0xf98c16ef, L:/127.0.0.1:37424 ! R:localhost/127.0.0.1:10000] INACTIVE
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelUnregistered
> INFO: [id: 0xf98c16ef, L:/127.0.0.1:37424 ! R:localhost/127.0.0.1:10000] UNREGISTERED
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler close
> INFO: [id: 0x40810d0c] CLOSE
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0x40810d0c] REGISTERED
> lut 01, 2021 12:59:53 PM io.tlf.monkeynetty.client.NettyClient setupUdp
> SEVERE: Failed to setup udp connection
> lut 01, 2021 12:59:53 PM io.tlf.monkeynetty.client.NettyClient catchNetworkError
> SEVERE: Network Client Error
> java.lang.IllegalStateException: executor not accepting a task
> 	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:61)
> 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
> 	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
> 	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
> 	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
> 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
> 	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
> 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
> 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelUnregistered
> INFO: [id: 0x40810d0c] UNREGISTERED
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelReadComplete
> INFO: [id: 0x30bede2b, L:/127.0.0.1:37416 - R:localhost/127.0.0.1:10000] READ COMPLETE
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler flush
> INFO: [id: 0x30bede2b, L:/127.0.0.1:37416 - R:localhost/127.0.0.1:10000] FLUSH
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0x30bede2b, L:/127.0.0.1:37416 ! R:localhost/127.0.0.1:10000] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelInactive
> INFO: [id: 0x30bede2b, L:/127.0.0.1:37416 ! R:localhost/127.0.0.1:10000] INACTIVE
> lut 01, 2021 12:59:53 PM io.tlf.monkeynetty.client.NettyClient handleInactiveConnection
> INFO: Connection inactive
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelUnregistered
> INFO: [id: 0x30bede2b, L:/127.0.0.1:37416 ! R:localhost/127.0.0.1:10000] UNREGISTERED
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0xc3d5da2f] REGISTERED
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler connect
> INFO: [id: 0xc3d5da2f] CONNECT: localhost/127.0.0.1:10000
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0xc3d5da2f, L:/127.0.0.1:37426 - R:localhost/127.0.0.1:10000] ACTIVE
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0xc3d5da2f, L:/127.0.0.1:37426 ! R:localhost/127.0.0.1:10000] USER_EVENT: SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0xc3d5da2f, L:/127.0.0.1:37426 ! R:localhost/127.0.0.1:10000] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelInactive
> INFO: [id: 0xc3d5da2f, L:/127.0.0.1:37426 ! R:localhost/127.0.0.1:10000] INACTIVE
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelUnregistered
> INFO: [id: 0xc3d5da2f, L:/127.0.0.1:37426 ! R:localhost/127.0.0.1:10000] UNREGISTERED
> lut 01, 2021 12:59:53 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0x428b3a1b] REGISTERED







on server side seen 2 errors, 

First one, "Przerwany potok" means "interrupted stream", it just probably mean that message was unable to send because client was closed. log:


> lut 01, 2021 12:58:57 PM io.netty.handler.logging.LoggingHandler flush
> INFO: [id: 0x5483cd18, L:/127.0.0.1:10000 - R:/127.0.0.1:37214] FLUSH
> Client disconnected: /127.0.0.1:37214
> lut 01, 2021 12:58:57 PM io.netty.handler.logging.LoggingHandler exceptionCaught
> INFO: [id: 0x5483cd18, L:/127.0.0.1:10000 ! R:/127.0.0.1:37214] EXCEPTION: java.io.IOException: Przerwany potok
> java.io.IOException: Przerwany potok
> 	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
> 	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
> 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
> 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
> 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
> 	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
> 	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
> 	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:2085)
> 	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:815)
> 	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:792)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
> 	at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:295)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
> 	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
> 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
> 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
> 	at io.tlf.monkeynetty.server.NettyConnection.send(NettyConnection.java:136)
> 	at io.tlf.monkeynetty.test.JmeServer$2.onMessage(JmeServer.java:69)
> 	at io.tlf.monkeynetty.server.NettyServer.receive(NettyServer.java:259)
> 	at io.tlf.monkeynetty.server.NettyServer$1$1.channelRead(NettyServer.java:404)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> lut 01, 2021 12:58:57 PM io.tlf.monkeynetty.server.NettyServer catchNetworkError
> WARNING: Network Server Error
> java.io.IOException: Przerwany potok
> 	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
> 	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
> 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
> 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
> 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
> 	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
> 	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
> 	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:2085)
> 	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:815)
> 	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:792)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
> 	at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:295)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
> 	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
> 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
> 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
> 	at io.tlf.monkeynetty.server.NettyConnection.send(NettyConnection.java:136)
> 	at io.tlf.monkeynetty.test.JmeServer$2.onMessage(JmeServer.java:69)
> 	at io.tlf.monkeynetty.server.NettyServer.receive(NettyServer.java:259)
> 	at io.tlf.monkeynetty.server.NettyServer$1$1.channelRead(NettyServer.java:404)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> lut 01, 2021 12:58:57 PM io.netty.handler.logging.LoggingHandler close
> INFO: [id: 0x5483cd18, L:/127.0.0.1:10000 ! R:/127.0.0.1:37214] CLOSE
> lut 01, 2021 12:58:57 PM io.netty.handler.logging.LoggingHandler write


Second one is also probably related to closed client connection, but im not sure why exception is thrown instead of just close it, but everything seems fine since Server do not crash.


> lut 01, 2021 12:59:51 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0x25d693c1, L:/127.0.0.1:10000 ! R:/127.0.0.1:37308] USER_EVENT: SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:51 PM io.netty.handler.logging.LoggingHandler exceptionCaught
> INFO: [id: 0x25d693c1, L:/127.0.0.1:10000 ! R:/127.0.0.1:37308] EXCEPTION: java.nio.channels.ClosedChannelException
> java.nio.channels.ClosedChannelException
> 	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> lut 01, 2021 12:59:51 PM io.tlf.monkeynetty.server.NettyServer catchNetworkError
> WARNING: Network Server Error
> java.nio.channels.ClosedChannelException
> 	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> lut 01, 2021 12:59:51 PM io.netty.handler.logging.LoggingHandler close
> INFO: [id: 0x25d693c1, L:/127.0.0.1:10000 ! R:/127.0.0.1:37308] CLOSE
> lut 01, 2021 12:59:51 PM io.netty.handler.logging.LoggingHandler userEventTriggered
> INFO: [id: 0x25d693c1, L:/127.0.0.1:10000 ! R:/127.0.0.1:37308] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
> lut 01, 2021 12:59:51 PM io.netty.handler.logging.LoggingHandler channelInactive
> INFO: [id: 0x25d693c1, L:/127.0.0.1:10000 ! R:/127.0.0.1:37308] INACTIVE

**Comment by tlf30** [comment]
This is great, thank you for testing this. Yes, I believe that you are correct on the exceptions/warnings. I can probably add in some try/catch logic into the handshake in the future to prevent errors when the client disconnects prematurely, but I will leave that for a different PR. 

I will merge this in. 

I will open a new issue for v0.1.1 discussion.

**Pull request merged**
