### PR TITLE
SSL Support

### PR DESCRIPTION
**Pull request by tlf30**
For #5 ssl support.

### CODE REVIEW

**Comment by tlf30** [comment]
@oxplay2 this is my design for an initial ssl support. Currently only supports self signed certificates, I am working on finding an example of using a user provided cert, but my google skills are failing me :P

Enable SSL by using the appropriate constructor on the server and client.

**Comment by oxplay2** [comment]
looks fine for me, i see you added just now custom cert support too :)

**Comment by tlf30** [comment]
OK, I think I have it figured out for custom key and cert. It was much simpler than I thought.
I will do some testing and then would you mind also testing?

**Comment by tlf30** [comment]
OK, should be ready for testing. I tested self signed cert, and updated the examples.

**Comment by oxplay2** [comment]
about custom certificate, i think only need to test, **if it is passed properly to Netty**, **nothing more**. Since Netty already had it tested.

**Comment by tlf30** [comment]
The reason for the test is to fail back to a self signed certificate. If both are passed in and are invalid, then netty will catch that. But this code assumes that if they are not provided that the developer wants to use a self signed certificate. 

I could change the check to failover to the self signed if only both are null, or only use self signed when the constructor that does not pass in the cert files is used.

**Comment by oxplay2** [comment]
its fine as it is now, with cert == null || key == null

but in this case, without generated cert, will be hard to test "not self signed case"

**Comment by tlf30** [comment]
I have modified the self cert gen conditions. What are your thoughts on this new approach?

**Comment by tlf30** [comment]
@oxplay2 does this look good to merge to you?
After this is merged, I am going to get started on javadocs.

**Comment by oxplay2** [comment]
looking at code, i didnt noticed any issues, so looks fine for me :+1: 

There is personal feeling about so many constructors, but well, its personal, i would just prefer use some methods like "setupSSL" be made before tcp/udp init instead 3 new constructors :)

but since its personal, everything looks fine.

**Comment by oxplay2** [comment]
Just now i thought,

later we could Create Settings class to be put into constructor like:

`public NettyClient(String service, int port, String server, Settings settings) {`

That could contain both yours PR and my recent PR settings like:
- connectionTimeout
- LoggingLevel
- SSL usage
- cert
- key
- etc settings

**Comment by tlf30** [comment]
I think that is a good idea. 
Is it possible to perhaps utilize the jme application settings to do this? 
Would you mind opening an issue for the settings?

I will merge this in.

**Comment by tlf30** [comment]
> looking at code, i didnt noticed any issues, so looks fine for me 👍
> 
> There is personal feeling about so many constructors, but well, its personal, i would just prefer use some methods like "setupSSL" be made before tcp/udp init instead 3 new constructors :)
> 
> but since its personal, everything looks fine.

In Outside, this networking system is not actually a appstate, it is what Outside calls an Engine, which actually gets its own thread, and had a complete lifecycle that is managed via load and unload methods. Every engine can be reloaded at any time without breaking any other engine. In Outside, many of the settings are not in constructors, but are setters that when used before the load phase will get applied to the engine, or when used after the engine has been loaded, will take effect upon the next reload.

**Comment by tlf30** [comment]
Tagging internal issue: 
https://git.liquidcrystalstudios.com/outside/outside/-/issues/172

**Pull request merged**
