### PR TITLE
Implement ping with IdleStateHandler to ensure connection is not broken.

### LINKED ISSUE #10: Issue: Connection Timeout do not await when connection server is not running.
As discussed, looks like we have issue with method:

`cfg.setConnectTimeoutMillis();`

that do not await when trying to connect to "offline" server

### PR DESCRIPTION
**Pull request by tlf30**
Closes #10 

This PR implements a ping sent between the server and client every 10 seconds to ensure the connection is open. After 30 seconds of no ping, the server or client will close the connection. If the client closes the connection, it will still attempt a reconnect with the server.

### CODE REVIEW

**Comment by tlf30** [comment]
@oxplay2 would you like to review this one when you get time?

**Comment by oxplay2** [comment]
CODE aspect:

looks fine, really nice.  :+1:

As i noticed you copied part from https://netty.io/4.1/api/io/netty/handler/timeout/IdleStateHandler.html docs.

Looking at google, some people were also using HeartbeatHandler, but docs demonstrate ChannelDuplexHandler so its "modern way" i assume.

IdleStateHandler send one-time event, its fine for ping, since ping refresh idle state.

Its also fine for client reconnect, since it change flag, so it should reconnect until connected (use default reconnect function)


TEST:

- Server -> Client ping works fine
- Client -> Server ping works fine
- Server close when 30 sec read idle -> dont know how to test, since when close Client, Server auto-close connection.
- Client reconnect when 30 sec read idle -> i closed server app, but client didnt try reconnect after 30 seconds. 
[it do try reconnect only when i pressed enter/space to send messages that were unable to send]
It is fine, but it could reconnect when there are no messages sent at all.

**Comment by tlf30** [comment]
Hmm, that is odd the client did not try a reconnect. I will test again. It should as reconnect should have been flagged to true...

**Comment by tlf30** [comment]
OK, I figured it out. There are two cases where the channel becomes inactive. The first is what we would expect, where it failed to get a message within the time frame. 
The second is very unintuitive. If the `ChannelDuplexHandler` detects that it lost the remote connection, it will instead trigger a `channelInactive` function, and not trigger the idle read. Unfortunately, it does not appear to be consistent as it relies on the host (in my case Window) to correctly determine the channel state and pass that to Netty. Sometimes the channel state is correctly determined, and sometimes it is not. 

To get around this, I simply reconnect on both situations.

**Pull request merged**
