### PR TITLE
Network message optimization

### PR DESCRIPTION
**Pull request by tlf30**
OK, this is an implementation to minimize network messages by remove the class name strings from them.
In this implementation, the server sends the class name and a UID to the client the first time that the class has been seen in that client's session. Meaning that once a class has been seen by the client, and the server sent it a UID, from then on the server only sends the UID.

Example:
The first send:
```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 00 36 05 73 72 02 00 26 69 6f 2e 74 6c 66 |...6.sr..&io.tlf|
|00000010| 2e 6d 6f 6e 6b 65 79 6e 65 74 74 79 2e 74 65 73 |.monkeynetty.tes|
|00000020| 74 2e 54 65 73 74 54 43 50 4d 65 73 73 61 67 65 |t.TestTCPMessage|
|00000030| 00 00 00 01 78 70 00 00 00 00                   |....xp....      |
+--------+-------------------------------------------------+----------------+
```
The second and onward sends:
```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 00 0e 05 73 72 01 00 00 00 00 78 70 00 00 |.....sr.....xp..|
|00000010| 00 00                                           |..              |
+--------+-------------------------------------------------+----------------+
```

@oxplay2 this needs heavily tested, would you mind trying to break it :P

### CODE REVIEW

**Comment by oxplay2** [comment]
please give me moment before merge, 

i would like to test things like for example:
- multiple clients connecting to single server.

and other things.

**Comment by oxplay2** [comment]
I have added following code for test purpose **into NetworkRegistrar -> public void unregister(Class<? extends NetworkMessage> clazz) {**


```
        System.out.println("Unregistering-----------");
        System.out.println("classUID");
        for (Map.Entry<String, Integer> entry : classUID.entrySet()) {
            String key = entry.getKey();
            Integer value = entry.getValue();
            System.out.println("key: " + key + " value:" + value);
        }
        System.out.println("uidClass");
        for (Map.Entry<Integer, String> entry : uidClass.entrySet()) {
            Integer key = entry.getKey();
            String value = entry.getValue();
            System.out.println("key: " + key + " value:" + value);
        }
```

I were doing log -> search for "Unregistering-----------" and were unable to find it,
even manually looking i dont see it.

LOGS:

```
lis 18, 2020 11:55:39 PM io.netty.handler.logging.LoggingHandler flush
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 - R:/127.0.0.1:55818] FLUSH
lis 18, 2020 11:55:39 PM io.netty.handler.logging.LoggingHandler channelReadComplete
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 - R:/127.0.0.1:55818] READ COMPLETE
lis 18, 2020 11:55:39 PM io.netty.handler.logging.LoggingHandler flush
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 - R:/127.0.0.1:55818] FLUSH
lis 18, 2020 11:55:48 PM io.netty.handler.logging.LoggingHandler channelReadComplete
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 - R:/127.0.0.1:55818] READ COMPLETE
lis 18, 2020 11:55:48 PM io.netty.handler.logging.LoggingHandler flush
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 - R:/127.0.0.1:55818] FLUSH
Client disconnected: /127.0.0.1:55818
lis 18, 2020 11:55:48 PM io.netty.handler.logging.LoggingHandler userEventTriggered
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 ! R:/127.0.0.1:55818] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
lis 18, 2020 11:55:48 PM io.netty.handler.logging.LoggingHandler channelInactive
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 ! R:/127.0.0.1:55818] INACTIVE
lis 18, 2020 11:55:48 PM io.netty.handler.logging.LoggingHandler channelUnregistered
INFO: [id: 0x2c798691, L:/127.0.0.1:10000 ! R:/127.0.0.1:55818] UNREGISTERED
```

**So about above, i assume it will cause memory leak when clients will connect/disconnect.**

About:

```
    private HashMap<String, Integer> classUID = new HashMap<>();
    private HashMap<Integer, String> uidClass = new HashMap<>();
    private volatile int uid = 0;
```

As i understand, Server will not increase uid, even when different client is connected, its globally right?

so ClientA + ClientB + ClientC will anyway have same uid, instead 3x uid, right?

I were thinking if change it to Long, but probably Integer is far enough, since it refer to "message classes amount" that hardly will exceed 1000 amount.

am i right?

**Comment by oxplay2** [comment]
yes, i understand why its made this way, and its good solution, each client can have different UID order for classes, and Server track it.

also yes, since it refer only to Class amount, even Short would be enough.

also im glad that there will be no memory leak, since i understang GC will clean it properly along with Connection itself.

But can we remove this "unregister" then? it seems like its not needed and might cause confuse when someone look at code and dont see usages :)

**Comment by tlf30** [comment]
> But can we remove this "unregister" then? it seems like its not needed and might cause confuse when someone look at code and dont see usages :)

Yes, there are a couple unused functions in there, I will remove them.

**Comment by oxplay2** [comment]
ok, you can remove unused code and maybe change to Short from Integer and i think we are good to go(merge :))

**Comment by tlf30** [comment]
Tagging internal issue:
https://git.liquidcrystalstudios.com/outside/outside/-/issues/173

**Pull request merged**
